FROM node:lts-buster-slim as ourabi

RUN mkdir /home/node/app/ && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node package*.json ./
USER node

RUN npm install --only=production && npm cache clean --force --loglevel=error
RUN npm install typescript

COPY --chown=node:node . .

RUN npm run build 

FROM node:lts-buster-slim

RUN mkdir /home/node/app/ && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY --from=ourabi --chown=node:node  /home/node/app/ .

USER node

EXPOSE 5000

CMD ["node","dist/index.js"]

